services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    depends_on:
      - redis
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
      PORT: 8000

  redis:
    image: redis:alpine

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    environment:
      HOST: "0.0.0.0"
      REACT_APP_API_BASE_URL: "http://localhost:8000"
